# Generated by Django 5.0.3 on 2024-03-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='gender',
        ),
    ]
