# Generated by Django 5.0.3 on 2024-03-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_form_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default=1, max_length=10),
        ),
    ]
